Repository bounswe/bounswe2023group7, pull requests merged in 2023-05, with the labels that each got.

#210 Practice app/feature/location history
  practice-app/client/package-lock.json
  practice-app/client/package.json
  practice-app/client/src/index.js
  practice-app/client/src/pages/elif/elif.js
  practice-app/client/src/pages/elif/elif.queries.js
  practice-app/server/package-lock.json
  practice-app/server/src/app.js
  practice-app/server/src/controllers/location.controller.js
  practice-app/server/src/models/location.model.js
  practice-app/server/src/routes/index.js
  practice-app/server/src/routes/location.routes.js
  practice-app/server/src/tests/location.test.js
Labels: type : enhancement, type : development, priority : urgent, status : in_progress, effort : low

#218 Practice app/feature/event location
  practice-app/client/.env
  practice-app/client/.gitignore
  practice-app/client/src/App.js
  practice-app/client/src/pages/furkan/createEvent.js
  practice-app/client/src/pages/furkan/event.js
  practice-app/client/src/pages/furkan/eventList.css
  practice-app/client/src/pages/furkan/furkan.js
  practice-app/client/src/pages/furkan/listEvent.js
  practice-app/client/src/pages/landingPage.js
  practice-app/package-lock.json
  practice-app/server/src/app.js
  practice-app/server/src/controllers/events.controller.js
  practice-app/server/src/models/event.model.js
  practice-app/server/src/routes/events.routes.js
  practice-app/server/src/routes/index.js
  practice-app/server/src/tests/events.test.js
Labels: status : need_review, milestone

#230 Practice app/feature/location history
  practice-app/server/.env.example
  practice-app/server/.gitignore
  practice-app/server/src/tests/location.test.js
Labels: type : development, priority : urgent, effort : low
